### ISSUE TITLE
SMTP emailing issues

### ISSUE THREAD

**Issue by esapy** [dsavell/docker-grav#1]
Dear David,

I discovered an issue related to the grav-admin module. The forgot password functionality (or any email notification) was not sending emails. The exception traceback routed the problem in the EHLO and HELO SMTP protocol commands resulting in a 501 (invalid domain address).

The nginx configuration /etc/nginx/conf.d/default.conf has a setting,

`server_name _;`

This should be changed to,

`server_name $hostname;`

After restarting the container, the email notifications began working as advertised.

I have a temporary solution in post-processing (which could be included in the Dockerfile):

`sed -i 's/server_name.*/server_name $hostname;/' /etc/nginx/conf.d/default.conf`

Thanks for the awesome docker. It's one of the few that's using the most recent version(s) (php + grav).

Cheers,

Hans

**Comment by dsavell** [comment]
Hey Hans,

Cheers for the update, funny that I received this email just in time, I am
making changes to the image currently I will try to include this also.

Regards,

**Comment by esapy** [comment]
Thanks!

**Comment by dsavell** [comment]
Fixed in latest release "The Refactor Release" thanks for contributing!
