### ISSUE TITLE
Complains of 'mbstring' not loaded.

### ISSUE THREAD

**Issue by aptonline** [dsavell/docker-grav#12]
Hi, I finally got around to testing the new images you made for the path issue I posted but upon using the new images I received an error saying that 'mbstring' was not loaded.

I fixed the issue by installing manually.

```
su
apt-get update
apt-get install php-mbstring
```

No sure if you need to check its installed as standard with the images.

**Comment by dsavell** [comment]
Hey Thanks again,

Are you able to provide the steps on how to repeat this?

**Comment by aptonline** [comment]
The `mbstring` error appeared as soon as I went to the front end url, also showed when I went to the admin login.  I downloaded the admin image to replace the one I already had.  After I installed mbstring using the above method it all worked as expected.

**Comment by Miroka96** [comment]
I have had the same error using the dsavell/grav:admin image and was able to fix it by running 'apt install php7.3-mbstring' inside the container and restarting the container

**Comment by Miroka96** [comment]
To prevent such errors in the future it might be an advantage to make the admin image inherit from the normal image

**Comment by dsavell** [comment]
Thank both, will take a look as soon as I can, I have raised and issue for inheritance that makes a lot of sense. https://github.com/dsavell/docker-grav/issues/14

Will get reviewing and rebuilding asap.

**Comment by dsavell** [comment]
Merged accepted, should now be resolved in latest tags, please repull
