### ISSUE TITLE
Reading nginx logs

### ISSUE THREAD

**Issue by hughbris** [dsavell/docker-grav#15]
Awesome image, thanks for creating it!

My Unix foo is pretty low and I'm not sure how to access the nginx error and access logs in my containers. Could you explain this? I can see they are symlinked to `stderr` and `stdout` but that doesn't help me (aforementioned embarrassing Unix foo). I can comment that part of the Dockerfile out in future containers, too, obviously.

**Comment by dsavell** [comment]
If you wish to read the logs outside from the container you can run the following: docker logs -f <container_name>

**Comment by dsavell** [comment]
Note: adding to usage section of the README.md
