### ISSUE TITLE
Adding an editor

### ISSUE THREAD

**Issue by hughbris** [dsavell/docker-grav#16]
I appreciate you are probably trying to keep this image very minimal. A couple of times, I've found it helpful (if not necessary) to install nano to hack at files outside of the suggested shared volumes. The ones I can think of are in the Grav root - `robots.txt` and the [multisite `setup.php` file](https://learn.getgrav.org/16/advanced/multisite-setup#snippets). (Actually a multisite image might be a good variant Dockerfile to add.)

Anyway, just thought you might consider adding `vim` or `nano` or whatever to the image :)

**Comment by dsavell** [comment]
Hey

Will keep this open to have a think on how I want to do this, concept is that a container should be ephemeral enough to recreate without editing, usually mounted in for example, so when you update the container configuration is kept.

**Comment by hughbris** [comment]
I'm happy if you want to close this now. It seems when I submitted this, I wasn't familiar with derivative Dockerfiles. It's easy enough to do:

```
FROM dsavell/grav
RUN \
  install_packages nano
```
And knowing this, I more often use it to create custom ephemeral containers without needing to edit container files.

**Comment by dsavell** [comment]
Great stuff! thanks

**Comment by hughbris** [comment]
You've done this now though? 3e8a3ca6

**Comment by dsavell** [comment]
Hey @hughbris - Yup, decided its been requested a few times, the people have spoken to add nano, so latest images have nano inside the image :)

**Comment by hughbris** [comment]
Giving people what they want! ;) No problems.
My comment was also motivated by wanting to link up issues, PRs, commits etc as much as possible.
