### ISSUE TITLE
Problem in Accessing

### ISSUE THREAD

**Issue by BigDC** [dsavell/docker-grav#31]
Hello, I created a container and I used the tag dsavell/grav:latest and it takes me to an already installed Grav site with no way to access the Admin.

So I created a different container and used the tag dsavell/grav:admin  And this just takes me to a 403 Forbidden Error fro, Nginx

I am wanting to add a container, and then be able to access the Grav admin so I can set everything up there.
Please help?
Thank You!

**Comment by dsavell** [comment]
Hey @BigDC 

Thanks for raising an issue, the `latest` tag is without the admin plugin if you want a complete clean container,

Can you repeat the steps for me here so I can try to recreate this issue?

**Comment by BigDC** [comment]
Ok on the latest tag, I understand.

As far as the dsavell/grav:admin it is now accessible., not sure what happened but it is now accessible.
