### ISSUE TITLE
Unable to `su` as user xyz

### ISSUE THREAD

**Issue by hughbris** [dsavell/docker-grav#36]
I can see that this is because [`useradd` uses `-s /bin/false`](https://github.com/dsavell/docker-grav/blob/6dde52d2ef724a84385d264b14f0a28afebdfc12/Dockerfile.gravcore#L5). Is there a good reason for this?

The reason I would find it handy is to run `bin/gpm` as the webserver user to avoid permission problems (which are fixed easily enough, but it's another step).

**Comment by dsavell** [comment]
Stale, please re-raise if still an issue

**Comment by hughbris** [comment]
I'm only using your image on one site right now because I can't get multisite to work on my [Caddy image](https://github.com/hughbris/cadaver) that I otherwise use nowadays.

> Stale, please re-raise if still an issue

Will do.

I must admit I've never understood conflating _old_ with "stale". There's a difference. That said, maybe my knowledge when I raised this issue has moved on and is now stale :) Perhaps what I wanted to do will work with `docker exec -u`.

Thanks for not using a stalebot too :)
