### ISSUE TITLE
-v path

### ISSUE THREAD

**Issue by p-marco** [dsavell/docker-grav#4]
Hello and thank you a lot for the job.
I am trying to expose a project by the -v attribute but I get only a blank page, while on the earlier version it worked as a charm. Am I missing something? Thank you

ps. the code I am using is:

```
docker create --name=test \ 
--restart=always \
-p 80:80 \
-v <path>:/var/www \
dsavell/grav
```

**Comment by dsavell** [comment]
Hey p-marco,

I will take a look at the volume asap.

Thanks for the contribution :)

**Comment by dsavell** [comment]
Hey p-marco,

latest release should resolve this:

please use the following:

```
docker create \
  --name=grav \
  --restart unless-stopped \
  -p 80:80 \
  -e DUID=1000 \
  -e DGID=1000 \
  -v /data/containers/grav/backup:/var/www/grav/backup \
  -v /data/containers/grav/logs:/var/www/grav/logs \
  -v /data/containers/grav/user:/var/www/grav/user \
  dsavell/grav
docker start grav
```

Regards,

**Comment by p-marco** [comment]
Hello dsavell, 
thanks a lot for your work!
