### ISSUE TITLE
Manifest for dsavell/grav:latest not found: manifest unknown

### ISSUE THREAD

**Issue by simplylu** [dsavell/docker-grav#49]
Tried to run your container alongside traefik and stumbled across the following issue:

`Error response from daemon: manifest for dsavell/grav:latest not found: manifest unknown: manifest unknown`

Since I don't wanna post my whole traefik config, I tried also your command for running the container via CLI. Same error.
The command I run:
```sh
docker create \
  --name=grav \
  --restart unless-stopped \
  -e DUID=1000 \
  -e DGID=1000 \
  -p 80:80 \
  -e GRAV_MULTISITE=subdirectory `# optional` \
  -e ROBOTS_DISALLOW=false `# optional` \
  -v /data/containers/grav/backup:/var/www/grav/backup \
  -v /data/containers/grav/logs:/var/www/grav/logs \
  -v /data/containers/grav/user:/var/www/grav/user \
  dsavell/grav:latest
```

Results in: 
```
Unable to find image 'dsavell/grav:latest' locally
Error response from daemon: manifest for dsavell/grav:latest not found: manifest unknown: manifest unknown
```

**System info**
```sh
user@host:~/tmp$ docker --version
Docker version 20.10.21, build baeda1f

user@host:~/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by jneeee** [comment]
I meet the same issue. Try pull dsavell/grav:admin instand of dsavell/grav:latest

**Comment by dsavell** [comment]
Heya @js-on I will update the documentation to reflect @jneeee comments thank you

**Comment by dsavell** [comment]
Updated docs

**Comment by hughbris** [comment]
FWIW I think it's worth considering aliasing a `latest` tag as that's become an expected convention (for tools and users).
