### ISSUE TITLE
Recreating container also recreates Home and Typography pages

### ISSUE THREAD

**Issue by Miroka96** [dsavell/docker-grav#6]
Hi,

I usually want to be able to delete and recreate containers as necessary... Unfortunately, on every initial start (at least of the init-admin script) a plain installation is copied over the previous data. During this process, some configurations get lost.

I would rather like the script to look for already existing data (without modifying it) and then to perform an update. I am just not completely sure how this could be done. Anyway, maybe someone can find a solution.
Nevertheless, I really like these docker containers!

Best,
Miroka

**Comment by dsavell** [comment]
Hey Miroka96

Thanks for the issue, looking into this now, its a good spot, no idea how I missed this, simple wrong condition in the init-core and init-admin this will be resolved as soon as I push a new image.

Regards,

**Comment by dsavell** [comment]
should be fixed now, let me know if you have any further issues.

New tags support this:

latest
admin-1.6.11
admin
core-1.6.11
1.6.11
