### ISSUE TITLE
Can’t access admin UI

### ISSUE THREAD

**Issue by aptonline** [dsavell/docker-grav#8]
I’ve installed as per instructions using the admin tag but when I visit `http://www.site.com/admin` I get a 404 error.

I attempted to install the admin panel via CLI but the commands for installing plugins don’t seem to be working.

What am I doing wrong?

**Comment by aptonline** [comment]
Ok I have fixed this issue as it turned out my permissions were 'very' wrong.

**Comment by FitzChevalerie-22** [comment]
That is to say?

I've the same problem but I don't understand...
